#!/usr/bin/env python3
"""Publish edge-exploits hosting provenance for the trend page.

Reads the LOCAL enrichment cache (cache/edge_exploits_asn.json, written by the
gitignored enrich_asns.py) and reshapes it into _data/edge_exploits_provenance.yml
for the page: per-month provider series for a stacked chart + a top-ASN table.

This is a deterministic site-data transform -- it reads only IP-free ASN/org COUNT
aggregates, makes no external calls, and touches no IPs or keys, so it lives in the
repo (decision #009). The enrichment that resolves IPs stays local. Runs locally
(the cache is gitignored); the page renders the committed YAML.

Usage: py scripts/transform_provenance.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CACHE = REPO / "cache" / "edge_exploits_asn.json"
OUT = REPO / "_data" / "edge_exploits_provenance.yml"
TOP_N = 6  # providers charted individually; the rest roll into "Other"

MONTHS = {"01": "Jan", "02": "Feb", "03": "Mar", "04": "Apr", "05": "May", "06": "Jun",
          "07": "Jul", "08": "Aug", "09": "Sep", "10": "Oct", "11": "Nov", "12": "Dec"}


class _QuoteCommaDumper(yaml.SafeDumper):
    """Single-quote strings with commas (AS org names like 'Amazon.com, Inc.') so
    they survive the YAML round-trip into Jekyll -- same reason as the CSV transform."""


def _repr_str(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data,
                                   style="'" if "," in data else None)


_QuoteCommaDumper.add_representer(str, _repr_str)


def month_label(ym: str) -> str:        # "2026-04" -> "Apr 2026"
    y, m = ym.split("-")
    return f"{MONTHS.get(m, m)} {y}"


def short(name: str) -> str:
    """Readable provider label from a Cymru AS name or a bulletproof-map name.
    'H2NEXUS-AS - H2NEXUS LTD, GB' -> 'H2NEXUS LTD'."""
    s = name.split(" - ", 1)[-1].strip()
    s = re.sub(r",\s*[A-Z]{2}$", "", s)     # drop trailing country code
    return s[:28]


def key(rec) -> str:
    return rec["asn"] if rec.get("asn") is not None else f"org:{rec.get('org')}"


def main() -> int:
    if not CACHE.exists():
        raise SystemExit(f"No enrichment cache at {CACHE.relative_to(REPO)}. "
                         "Run enrich_asns.py first (local).")
    data = json.loads(CACHE.read_text(encoding="utf-8"))
    months = sorted(data.get("months", {}).keys())
    asn_totals = data.get("asn_totals", [])

    by_month_key = {ym: {key(r): r["events"] for r in recs}
                    for ym, recs in data.get("months", {}).items()}
    month_total = {ym: sum(v.values()) for ym, v in by_month_key.items()}

    top = asn_totals[:TOP_N]
    top_keys = {key(r) for r in top}
    providers = []
    for r in top:
        k = key(r)
        providers.append({
            "name": short(r["name"]), "asn": r["asn"], "bulletproof": bool(r["bulletproof"]),
            "total": r["events"], "display": f'{r["events"]:,}',
            "series": [by_month_key.get(ym, {}).get(k, 0) for ym in months],
        })
    other_series = [month_total.get(ym, 0)
                    - sum(by_month_key.get(ym, {}).get(k, 0) for k in top_keys)
                    for ym in months]
    if sum(other_series) > 0:
        providers.append({"name": "Other", "asn": None, "bulletproof": False,
                          "total": sum(other_series), "display": f"{sum(other_series):,}",
                          "series": other_series})

    table = [{"name": short(r["name"]), "asn": r["asn"], "bulletproof": bool(r["bulletproof"]),
              "events": r["events"], "display": f'{r["events"]:,}'} for r in asn_totals[:10]]

    out = {
        "meta": {
            "source": data.get("source", "Defused honeypot IPs enriched via Team Cymru"),
            "generated": data.get("generated"),
            "window": f"{month_label(months[0])} - {month_label(months[-1])}" if months else "n/a",
            "cumulative_unique_ips": data.get("cumulative_unique_ips"),
            "bulletproof_pct": data.get("bulletproof_pct", 0),
            "total_events": data.get("total_events"),
        },
        "month_labels": [month_label(m) for m in months],
        "providers": providers,
        "asn_totals": table,
    }
    OUT.write_text(
        "# Generated by scripts/transform_provenance.py from the LOCAL enrichment cache.\n"
        "# Aggregates only (ASN / org / counts) -- no IPs. Enrichment is local (decision #009).\n\n"
        + yaml.dump(out, Dumper=_QuoteCommaDumper, sort_keys=False, allow_unicode=True,
                    width=200, default_flow_style=False),
        encoding="utf-8", newline="\n")
    print(f"OK wrote {OUT.relative_to(REPO)} "
          f"({len(months)} month(s), {len(providers)} providers charted, "
          f"{len(table)} in table)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
